# Generated by Django 4.0.3 on 2023-11-24 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePlayingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ko-KR', 'Korean'), ('en-US', 'English'), ('ja-JP', 'Japanese')], default='ko-KR', max_length=10, verbose_name='대화 언어')),
                ('situation', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='상황')),
                ('my_role', models.CharField(max_length=100, verbose_name='내 역할')),
                ('gpt_role', models.CharField(max_length=100, verbose_name='GPT 역할')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
