# Generated by Django 4.0.3 on 2023-11-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_roleplayingroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleplayingroom',
            name='user',
        ),
    ]
