# Generated by Django 4.0.3 on 2023-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_roleplayingroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingroom',
            name='language',
            field=models.CharField(max_length=10, verbose_name='대화 언어'),
        ),
    ]
