# Generated by Django 4.0.3 on 2023-11-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_roleplayingroom_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleplayingroom',
            old_name='user_id',
            new_name='user',
        ),
    ]
