# Generated by Django 4.0.3 on 2023-11-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_roleplayingroom_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleplayingroom',
            options={},
        ),
    ]
