# Generated by Django 4.0.3 on 2023-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_roleplayingroom_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingroom',
            name='chat_history',
            field=models.TextField(default=None, verbose_name='채팅 기록'),
        ),
    ]
